name = "stock-analysis-app"
compatibility_date = "2024-01-01"

# Cloudflare Pages configuration
pages_build_output_dir = "public"

# Environment variables (these will be set in Cloudflare dashboard)
[env.production]
vars = { ENVIRONMENT = "production" }

[env.preview]
vars = { ENVIRONMENT = "preview" }

# You'll need to set the BACKEND_URL environment variable in Cloudflare Pages dashboard
# Example: BACKEND_URL = "https://your-backend.onrender.com" or Railway/Fly.io URL
